// Code generated by edbml gen from schema.dbml; DO NOT EDIT.

// Package itest contains data models generated from schema.dbml.
//
// Integration-test fixture for the v0 CRUD generator.
package itest

import (
	"github.com/Piechutowski/not-an-orm/rt"
	"time"
)

// OrderStatus is the order_status enum.
type OrderStatus string

const (
	OrderStatusPending OrderStatus = "pending"
	OrderStatusShipped OrderStatus = "shipped"
	// Terminal state
	OrderStatusDelivered OrderStatus = "delivered"
)

// User is a row of the users table.
type User struct {
	ID    int32  `db:"id" json:"id"`
	Email string `db:"email" json:"email"`
	Name  string `db:"name" json:"name"`
	// NULL until the user writes one
	Bio       rt.Null[string] `db:"bio" json:"bio"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

// Order is a row of the orders table.
type Order struct {
	ID       int32              `db:"id" json:"id"`
	UserID   int32              `db:"user_id" json:"user_id"`
	Status   OrderStatus        `db:"status" json:"status"`
	Total    string             `db:"total" json:"total"`
	PlacedAt rt.Null[time.Time] `db:"placed_at" json:"placed_at"`
}

// UserTag is a row of the user_tags table.
type UserTag struct {
	UserID int32  `db:"user_id" json:"user_id"`
	Tag    string `db:"tag" json:"tag"`
}
